openapi: 3.0.0
info:
  version: Unstable
  title: Hotels API for external clients
  description: This API can be used by external clients.
servers:
  - url: 'https://master.hotels.stage.thebestagent.pro'
    description: master
paths:
  /public/external/v1/search/hotels:
    post:
      tags:
        - Hotels Paths
      summary: Hotels Search
      description: 'Search for available properties based on location, dates, and required rooms. This action starts a session on the backend to track the booking process.'
      requestBody:
        description: |-
          * **check_in**: The start date for the booking period. This date can be set up to 365 days in the future, allowing users to plan for trips up to a year ahead.
          * **check_out**: The end date for the booking period. This date must be at least 1 day after the **check_in** date and no more than 90 days after, ensuring that the booking duration is reasonable and within a 3-month limit.
        content:
          application/json;charset=utf-8:
            schema:
              $ref: '#/components/schemas/APISearchRequest_APISearchTypeExt'
            examples:
              Search by radius in London:
                value:
                  check_in: '2016-07-22'
                  check_out: '2016-07-27'
                  rooms:
                    - adults_count: 1
                      kids_ages:
                        - 1
                  search_by:
                    center:
                      latitude: 51.5074
                      longitude: -0.1278
                    name: London
                    radius: 10000
              Search several rooms in London:
                value:
                  check_in: '2016-07-22'
                  check_out: '2016-07-27'
                  rooms:
                    - adults_count: 1
                      kids_ages:
                        - 1
                    - adults_count: 1
                      kids_ages:
                        - 17
                  search_by:
                    center:
                      latitude: 51.5074
                      longitude: -0.1278
                    name: London
                    radius: 10000
              Search rooms by rectangle in New York:
                value:
                  check_in: '2016-07-22'
                  check_out: '2016-07-27'
                  rooms:
                    - adults_count: 1
                      kids_ages:
                        - 1
                    - adults_count: 1
                      kids_ages:
                        - 17
                  search_by:
                    ne_corner:
                      latitude: 40.7263
                      longitude: -73.9885
                    sw_corner:
                      latitude: 40.6993
                      longitude: -74.0235
                    place_name: New York City
      responses:
        '200':
          description: |-
            The Search API returns a list of properties that match the specified search parameters, each accompanied by a preliminary room offer. This initial offer provides essential details such as pricing, cancellation policies, and room specifics, allowing clients to make informed choices before proceeding with a booking.

            In addition, the API generates and returns a **session_id** at the start of the search. This **session_id** is used to track and manage the session seamlessly from the initial search phase through to the booking completion, ensuring all related actions are correctly associated with the user’s session.
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/APISearchResponse'
        '400':
          description: Invalid `body`
      security:
        - air-public-oauth: []
      servers:
        - url: 'https://master.hotels.stage.thebestagent.pro'
          description: master
  /public/external/v1/book/create:
    post:
      tags:
        - Hotels Paths
      summary: Prepare for Booking
      description: Checking data for Booking and create order in Hotels backend. It doesn't make real booking
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: '#/components/schemas/APIBookRequest_APIPaymentCredsP'
      responses:
        '200':
          description: ''
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/UUID'
        '400':
          description: Invalid `body`
      security:
        - air-public-oauth: []
      servers:
        - url: 'https://master.hotels.stage.thebestagent.pro'
          description: master
  '/public/external/v1/order/{order_id}/book':
    post:
      tags:
        - Hotels Paths
      summary: Process Hotels Booking
      description: Process Booking using data for order. Run it after book/create
      parameters:
        - name: order_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: '#/components/schemas/APIPaymentCredsP'
      responses:
        '200':
          description: ''
          content:
            application/json;charset=utf-8: {}
        '400':
          description: Invalid `body`
        '404':
          description: '`order_id` not found'
      security:
        - air-public-oauth: []
      servers:
        - url: 'https://master.hotels.stage.thebestagent.pro'
          description: master
  '/public/external/v1/order/{order_id}/cancel':
    patch:
      tags:
        - Hotels Paths
      parameters:
        - name: confirmation
          in: query
          required: false
          schema:
            type: string
        - name: order_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: ''
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/APIOrderDetails'
        '400':
          description: Invalid `confirmation`
        '404':
          description: '`order_id` not found'
      security:
        - air-public-oauth: []
      servers:
        - url: 'https://master.hotels.stage.thebestagent.pro'
          description: master
  '/public/external/v1/order/{order_id}/details':
    get:
      tags:
        - Hotels Paths
      summary: Order details
      description: Get details of order.
      parameters:
        - name: order_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: ''
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/APIOrderDetailsExt'
        '404':
          description: '`order_id` not found'
      security:
        - air-public-oauth: []
      servers:
        - url: 'https://master.hotels.stage.thebestagent.pro'
          description: master
  '/public/external/v1/order/{order_id}/sync_status':
    post:
      tags:
        - Hotels Paths
      parameters:
        - name: confirmation
          in: query
          required: false
          schema:
            type: string
        - name: order_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: ''
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/APIOrderDetailsExt'
        '400':
          description: Invalid `confirmation`
        '404':
          description: '`order_id` not found'
      security:
        - air-public-oauth: []
      servers:
        - url: 'https://master.hotels.stage.thebestagent.pro'
          description: master
  /public/external/v1/search/get_rooms:
    post:
      tags:
        - Hotels Paths
      summary: Offers for Hotel
      description: Get offers for booking for one selected Hotel.
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: '#/components/schemas/APIGetRoomsRequest'
      responses:
        '200':
          description: ''
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/APIGetRoomsResponse'
        '400':
          description: Invalid `body`
      security:
        - air-public-oauth: []
      servers:
        - url: 'https://master.hotels.stage.thebestagent.pro'
          description: master
  /public/external/v1/search/hotel_properties:
    post:
      tags:
        - Hotels Paths
      summary: Hotels properties
      description: 'Get hotel properties (images, facilities, descriptions, policies etc) for the list of hotels. Usually we search for available hotels and then get their property while scrolling etc.'
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              type: array
              items:
                type: string
      responses:
        '200':
          description: ''
          content:
            application/json;charset=utf-8:
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/APIHotelProperties'
        '400':
          description: Invalid `body`
      security:
        - air-public-oauth: []
      servers:
        - url: 'https://master.hotels.stage.thebestagent.pro'
          description: master
tags:
  - name: Hotels Paths
components:
  securitySchemes:
    air-public-oauth:
      type: http
      description: Bearer token
      scheme: bearer
  schemas:
    APISearchRequest_APISearchTypeExt:
      type: object
      properties:
        check_in:
          $ref: '#/components/schemas/Day'
        check_out:
          $ref: '#/components/schemas/Day'
        rooms:
          type: array
          minItems: 1
          maxItems: 4
          items:
            $ref: '#/components/schemas/APIRoomRequest'
        search_by:
          $ref: '#/components/schemas/APISearchTypeExt'
      required:
        - check_in
        - check_out
        - rooms
        - search_by
    Day:
      type: string
      description: 'Date, formatted as YYYY-MM-DD (e.g., “2016-07-22”)'
      format: date
      example: '2016-07-22'
    APIRoomRequest:
      type: object
      properties:
        adults_count:
          type: integer
          minimum: 1
          maximum: 10
        kids_ages:
          type: array
          maxItems: 10
          items:
            type: integer
            minimum: 1
            maximum: 17
      required:
        - adults_count
        - kids_ages
    APISearchTypeExt:
      oneOf:
        - $ref: '#/components/schemas/APIRadiusSearch'
        - $ref: '#/components/schemas/APIRectangleSearch'
    APIRadiusSearch:
      type: object
      title: Radius Search
      description: Search by radius
      properties:
        center:
          $ref: '#/components/schemas/Location'
        name:
          type: string
        radius:
          type: integer
          description: meters
          minimum: 0
          maximum: 50000
      required:
        - center
        - name
        - radius
    Location:
      type: object
      properties:
        latitude:
          type: number
          example: 51.506958
        longitude:
          type: number
          example: -0.124813
      required:
        - latitude
        - longitude
    APIRectangleSearch:
      type: object
      title: Rectangle Search
      description: Search by rectangle
      properties:
        ne_corner:
          $ref: '#/components/schemas/Location'
        sw_corner:
          $ref: '#/components/schemas/Location'
        place_name:
          type: string
      required:
        - ne_corner
        - sw_corner
        - place_name
    APISearchResponse:
      type: object
      properties:
        filters:
          type: array
          items:
            $ref: '#/components/schemas/APIFilterCategory'
        hotels:
          type: array
          items:
            $ref: '#/components/schemas/APIHotel'
        session_id:
          $ref: '#/components/schemas/UUID'
      required:
        - filters
        - hotels
        - session_id
    APIFilterCategory:
      type: object
      properties:
        facility_type:
          $ref: '#/components/schemas/APIFacilityType'
        groups:
          type: array
          items:
            $ref: '#/components/schemas/APIFilterGroup'
        name:
          type: string
        priority:
          type: integer
      required:
        - groups
        - name
        - priority
    APIFacilityType:
      type: string
      enum:
        - room
        - hotel
    APIFilterGroup:
      type: object
      properties:
        hotel_ids:
          type: array
          items:
            type: string
        id:
          $ref: '#/components/schemas/UUID'
        name:
          type: string
        priority:
          type: integer
      required:
        - hotel_ids
        - id
        - name
        - priority
    UUID:
      type: string
      format: uuid
      example: 00000000-0000-0000-0000-000000000000
    APIHotel:
      type: object
      description: 'A collection of properties that match the search parameters. Each includes detailed information about the property, as well as preliminary pricing details for available room offers.'
      properties:
        address:
          type: string
          example: '"18/21 Northumberland Avenue"'
        chain_name:
          type: string
          example: '"Ascott"'
        city_name:
          type: string
          example: '"London"'
        country_code:
          type: string
          example: '"GB"'
        display_name:
          type: string
          example: '"Citadines South Kensington London"'
        has_free_cancellation:
          type: boolean
        hotel_id:
          type: string
          description: readable ID of the hotel
          example: '"39670730"'
        location:
          $ref: '#/components/schemas/Location'
        property_type:
          type: string
          example: '"Aparthotel"'
        room_offer:
          $ref: '#/components/schemas/APISearchRoomOffer'
        star_rating:
          type: integer
          description: 0 - means that hotel has no stars
          minimum: 0
          maximum: 5
          example: 4
        state:
          type: string
          example: '"England"'
      required:
        - country_code
        - display_name
        - has_free_cancellation
        - hotel_id
        - room_offer
    APISearchRoomOffer:
      type: object
      description: 'Information about the room offer for the requested set of rooms, providing price and additional booking details'
      properties:
        dtt_pricing:
          $ref: '#/components/schemas/APIDttPricing'
        meal_plan:
          $ref: '#/components/schemas/MealPlan'
        simple_price:
          type: number
          multipleOf: 0.01
        supplier_id:
          type: string
        supplier_name:
          type: string
      required:
        - dtt_pricing
        - supplier_id
        - supplier_name
    APIDttPricing:
      type: object
      properties:
        additional_fees:
          type: array
          items:
            $ref: '#/components/schemas/APITaxesAndFees'
        dtt_fee:
          type: number
          multipleOf: 0.01
        rate:
          type: number
          multipleOf: 0.01
        special_taxes:
          type: array
          items:
            $ref: '#/components/schemas/APITaxesAndFees'
        tax:
          type: number
          multipleOf: 0.01
        total_special_tax:
          type: number
          multipleOf: 0.01
      required:
        - additional_fees
        - dtt_fee
        - rate
        - special_taxes
        - tax
        - total_special_tax
    APITaxesAndFees:
      type: object
      properties:
        currency:
          type: string
        fee_title:
          type: string
        frequency_type:
          type: string
        is_included_in_price:
          type: boolean
        is_value_percentage:
          type: boolean
        unit_type:
          type: string
        value:
          type: string
    MealPlan:
      type: string
      enum:
        - all_inclusive
        - breakfast_included
        - full_board
        - half_board
        - dinner_included
        - room_only
        - self_catering
    APIBookRequest_APIPaymentCredsP:
      type: object
      properties:
        agency_fee:
          type: number
          multipleOf: 0.01
        booking:
          $ref: '#/components/schemas/APIHotelBookRequest'
        check_in:
          $ref: '#/components/schemas/Day'
        check_out:
          $ref: '#/components/schemas/Day'
        payment_commission:
          type: number
          multipleOf: 0.01
        payment_creds:
          $ref: '#/components/schemas/APIPaymentCredsP'
        session_id:
          $ref: '#/components/schemas/UUID'
        total_price:
          type: number
          multipleOf: 0.01
      required:
        - agency_fee
        - booking
        - check_in
        - check_out
        - payment_commission
        - payment_creds
        - session_id
        - total_price
    APIHotelBookRequest:
      type: object
      properties:
        guests:
          $ref: '#/components/schemas/Guests'
        hotel_id:
          type: string
        package_id:
          type: string
        rooms_remarks:
          type: array
          items:
            type: array
            minItems: 2
            maxItems: 2
      required:
        - guests
        - hotel_id
        - package_id
        - rooms_remarks
    Guests:
      type: object
      properties:
        contact_data:
          $ref: '#/components/schemas/GuestContacts'
        lead_guest:
          type: array
          minItems: 2
          maxItems: 2
        room_guests:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/RoomGuestsInfo'
      required:
        - contact_data
        - lead_guest
        - room_guests
    GuestContacts:
      type: object
      properties:
        email:
          type: string
        phone:
          type: string
      required:
        - email
        - phone
    RoomGuestsInfo:
      type: object
      properties:
        adults_count:
          type: integer
          minimum: 0
          maximum: 255
        kids_ages:
          type: array
          items:
            type: integer
            minimum: 0
            maximum: 17
        known_guests:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/Guest'
        room_id:
          type: string
      required:
        - known_guests
        - room_id
    Guest:
      type: object
      properties:
        address_line:
          type: string
        age:
          $ref: '#/components/schemas/AgeOrBirth'
        city:
          type: string
        first_name:
          type: string
        gender:
          $ref: '#/components/schemas/Gender'
        guest_id:
          $ref: '#/components/schemas/UUID'
        last_name:
          type: string
        middle_name:
          type: string
        nationality:
          type: string
        postal_code:
          type: string
        street:
          type: string
      required:
        - age
        - first_name
        - guest_id
        - last_name
        - nationality
    AgeOrBirth:
      oneOf:
        - type: object
          title: Age
          properties:
            age:
              $ref: '#/components/schemas/GuestAge'
          required:
            - age
        - type: object
          title: Birthday
          properties:
            birthday:
              $ref: '#/components/schemas/Day'
          required:
            - birthday
    GuestAge:
      oneOf:
        - type: string
          enum:
            - adult
          title: AdultAge
        - type: integer
          title: TChildAge
          minimum: 0
          maximum: 17
    Gender:
      type: string
      enum:
        - male
        - female
    APIPaymentCredsP:
      oneOf:
        - type: string
          enum:
            - cheque
          title: APIPPaymentCheque
        - $ref: '#/components/schemas/CreditCardInfo'
    CreditCardInfo:
      type: object
      properties:
        billing_address:
          $ref: '#/components/schemas/APIBillingAddress'
        credit_card:
          $ref: '#/components/schemas/CreditCard'
      required:
        - billing_address
        - credit_card
    APIBillingAddress:
      type: object
      properties:
        address_line:
          type: string
        city:
          type: string
        country_code:
          type: string
        phone:
          type: string
        state:
          type: string
        zip_code:
          type: string
      required:
        - address_line
        - city
        - country_code
        - phone
        - zip_code
    CreditCard:
      type: object
      properties:
        expiration_date:
          type: string
        holder_name:
          type: string
        number:
          type: string
        security:
          type: string
        zip_code:
          type: string
      required:
        - expiration_date
        - holder_name
        - number
    APIOrderDetails:
      type: object
      properties:
        admin_comment:
          type: string
        agency_id:
          $ref: '#/components/schemas/UUID'
        agent_id:
          $ref: '#/components/schemas/UUID'
        booking_pricing:
          $ref: '#/components/schemas/APIOrderPricing'
        booking_remarks:
          type: string
        cancellation_policy:
          $ref: '#/components/schemas/OrderCancellations'
        check_in_date:
          $ref: '#/components/schemas/Day'
        check_out_date:
          $ref: '#/components/schemas/Day'
        contact_email:
          type: string
        contact_phone:
          type: string
        created_at:
          $ref: '#/components/schemas/UTCTime'
        has_resort_fees_warning:
          type: boolean
        hotel:
          $ref: '#/components/schemas/APIOrderHotel'
        id:
          $ref: '#/components/schemas/UUID'
        is_external:
          type: boolean
        legacy_contact_phone:
          type: string
        payments:
          type: array
          items:
            $ref: '#/components/schemas/APIOrderPayment'
        readable_id:
          type: integer
        refund_pricing:
          $ref: '#/components/schemas/APIOrderPricing'
        rooms:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/APIOrderRoom'
        supplier:
          $ref: '#/components/schemas/APIOrderSupplier'
        supplier_order_id:
          type: string
        updated_at:
          $ref: '#/components/schemas/UTCTime'
      required:
        - agency_id
        - booking_pricing
        - cancellation_policy
        - check_in_date
        - check_out_date
        - contact_email
        - contact_phone
        - created_at
        - has_resort_fees_warning
        - hotel
        - id
        - is_external
        - payments
        - readable_id
        - rooms
        - updated_at
    APIOrderPricing:
      type: object
      properties:
        additional_fees:
          type: array
          items:
            $ref: '#/components/schemas/AdditionalFee'
        agency_commission:
          type: number
          multipleOf: 0.01
        dtt_fee:
          type: number
          multipleOf: 0.01
        final_tax:
          type: number
          multipleOf: 0.01
        payment_commission:
          type: number
          multipleOf: 0.01
        rate:
          type: number
          multipleOf: 0.01
        special_tax:
          type: number
          multipleOf: 0.01
        total_price:
          type: number
          multipleOf: 0.01
      required:
        - additional_fees
        - agency_commission
        - dtt_fee
        - final_tax
        - payment_commission
        - rate
        - special_tax
        - total_price
    AdditionalFee:
      type: object
      properties:
        room_name:
          type: string
        title:
          type: string
        unit_type:
          $ref: '#/components/schemas/FeeUnitType'
        units:
          type: string
        value:
          type: number
          multipleOf: 0.01
      required:
        - title
        - units
        - value
    FeeUnitType:
      type: string
      enum:
        - other
        - not_applicable
        - not_specified
        - per_child
        - per_adult
        - per_night
        - per_room
        - per_stay
        - per_person
        - per_occurrence
        - per_item
        - per_reservation
    OrderCancellations:
      type: object
      properties:
        first_cancellation:
          $ref: '#/components/schemas/CancellationPolicy'
        refundability:
          $ref: '#/components/schemas/Refundability'
        rest_cancellations:
          type: array
          items:
            $ref: '#/components/schemas/CancellationPolicy'
      required:
        - first_cancellation
        - refundability
        - rest_cancellations
    CancellationPolicy:
      type: object
      properties:
        date_from:
          $ref: '#/components/schemas/UTCTime'
        date_to:
          $ref: '#/components/schemas/UTCTime'
        fee_details:
          $ref: '#/components/schemas/CancellationFeeDetails'
        total_fee:
          type: number
          multipleOf: 0.01
      required:
        - date_from
        - date_to
        - fee_details
        - total_fee
    UTCTime:
      type: string
      format: 'yyyy-mm-ddThh:MM:ssZ'
      example: '2016-07-22T00:00:00Z'
    CancellationFeeDetails:
      type: object
      properties:
        agency_cancellation_fee:
          type: number
          multipleOf: 0.01
        dtt_cancellation_fee:
          type: number
          multipleOf: 0.01
        hotel_cancellation_fee:
          type: number
          multipleOf: 0.01
        payment_cancellation_fee:
          type: number
          multipleOf: 0.01
      required:
        - hotel_cancellation_fee
    Refundability:
      oneOf:
        - type: object
          title: NonRefundable
          properties:
            tag:
              type: string
              enum:
                - non_refundable
          required:
            - tag
        - type: object
          title: PartiallyRefundable
          properties:
            tag:
              type: string
              enum:
                - partially_refundable
          required:
            - tag
        - type: object
          title: RefundableTill
          properties:
            contents:
              $ref: '#/components/schemas/UTCTime'
            tag:
              type: string
              enum:
                - refundable_till
          required:
            - contents
            - tag
    APIOrderHotel:
      type: object
      properties:
        address:
          type: string
        coordinates:
          $ref: '#/components/schemas/Location'
        facilities:
          type: array
          items:
            type: string
        id:
          type: string
        name:
          type: string
        phone:
          type: string
        property_category:
          $ref: '#/components/schemas/PropertyType'
        property_descriptions:
          type: array
          items:
            $ref: '#/components/schemas/PropertyDescription'
        star_rating:
          type: integer
          minimum: -9223372036854776000
          maximum: 9223372036854776000
        zh_order_id:
          type: string
        zip_code:
          type: string
      required:
        - coordinates
        - facilities
        - id
        - name
        - property_category
        - property_descriptions
    PropertyType:
      type: string
      enum:
        - property_hotel
        - property_apartment
        - property_hostel
        - property_guesthouse
        - property_aparthotel
        - property_other
    PropertyDescription:
      type: object
      properties:
        group:
          type: string
        paragraphs:
          type: array
          items:
            type: string
        subgroup:
          type: string
        title:
          type: string
      required:
        - group
        - paragraphs
    APIOrderPayment:
      type: object
      properties:
        amount:
          type: number
          multipleOf: 0.01
        anti_fraud_decision:
          $ref: '#/components/schemas/APIAntiFraudDecision'
        due_date:
          $ref: '#/components/schemas/Day'
        id:
          $ref: '#/components/schemas/UUID'
        pan_cc:
          type: string
        status:
          $ref: '#/components/schemas/APIOrderPaymentStatus'
        typ:
          $ref: '#/components/schemas/APIHotelsPaymentType'
        updated_at:
          $ref: '#/components/schemas/UTCTime'
      required:
        - amount
        - id
        - status
        - typ
        - updated_at
    APIAntiFraudDecision:
      type: string
      enum:
        - approved
        - declined_fraudulent
        - declined_high_risk
        - declined_considerable_risk
        - unknown
    APIOrderPaymentStatus:
      type: string
      enum:
        - pending
        - processing
        - charged
        - authorized
        - canceled
        - rejected
        - error
        - issued
    APIHotelsPaymentType:
      type: string
      enum:
        - merchant_charge
        - check_to_agency
        - agency_charge
        - check_from_agency
        - merchant_refund
        - refund_check_from_agency
        - agency_refund
        - refund_check_to_agency
    APIOrderRoom:
      type: object
      properties:
        adult_guests:
          type: integer
          minimum: 0
          maximum: 255
        bed_type:
          type: string
        booking_remarks:
          type: array
          items:
            type: string
        booking_status:
          $ref: '#/components/schemas/APIRoomStatus'
        facilities:
          type: array
          items:
            type: string
        id:
          $ref: '#/components/schemas/UUID'
        kids_ages:
          type: array
          items:
            type: integer
            minimum: 0
            maximum: 255
        lead_guest:
          $ref: '#/components/schemas/APIOrderGuest'
        meal_plan:
          $ref: '#/components/schemas/MealPlan'
        name:
          type: string
        refund_status:
          $ref: '#/components/schemas/APIRefundStatus'
        room_src_id:
          type: string
        status_updated_at:
          $ref: '#/components/schemas/UTCTime'
        supplier_segment_id:
          type: string
        tv_segment_id:
          type: integer
      required:
        - adult_guests
        - facilities
        - id
        - kids_ages
        - lead_guest
        - name
        - room_src_id
        - status_updated_at
    APIRoomStatus:
      type: string
      enum:
        - pending
        - rejected
        - processing_booking
        - booked
        - processing_cancel
        - cancel_error
        - booking_error
        - canceled
    APIOrderGuest:
      type: object
      properties:
        last_name:
          type: string
        name:
          type: string
        nationality:
          type: string
        second_name:
          type: string
        title:
          type: string
      required:
        - last_name
        - name
        - nationality
        - title
    APIRefundStatus:
      type: string
      enum:
        - refund_processing
        - refund_issued
    APIOrderSupplier:
      type: object
      properties:
        booking_source:
          $ref: '#/components/schemas/APIHotelBookingSource'
        email:
          type: string
        name:
          type: string
        phone:
          type: string
        website:
          type: string
      required:
        - name
    APIHotelBookingSource:
      type: string
      enum:
        - tv
        - zh
    APIOrderDetailsExt:
      type: object
      properties:
        admin_comment:
          type: string
        agency_id:
          $ref: '#/components/schemas/UUID'
        agent_id:
          $ref: '#/components/schemas/UUID'
        booking_pricing:
          $ref: '#/components/schemas/APIOrderPricing'
        booking_remarks:
          type: string
        cancellation_policy:
          $ref: '#/components/schemas/OrderCancellations'
        check_in_date:
          $ref: '#/components/schemas/Day'
        check_out_date:
          $ref: '#/components/schemas/Day'
        contact_email:
          type: string
        contact_phone:
          type: string
        created_at:
          $ref: '#/components/schemas/UTCTime'
        has_resort_fees_warning:
          type: boolean
        hotel:
          $ref: '#/components/schemas/APIOrderHotelExt'
        id:
          $ref: '#/components/schemas/UUID'
        legacy_contact_phone:
          type: string
        payments:
          type: array
          items:
            $ref: '#/components/schemas/APIOrderPayment'
        readable_id:
          type: integer
        refund_pricing:
          $ref: '#/components/schemas/APIOrderPricing'
        rooms:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/APIOrderRoomExt'
        supplier:
          $ref: '#/components/schemas/APIOrderSupplier'
        supplier_order_id:
          type: string
        updated_at:
          $ref: '#/components/schemas/UTCTime'
      required:
        - agency_id
        - booking_pricing
        - cancellation_policy
        - check_in_date
        - check_out_date
        - contact_email
        - contact_phone
        - created_at
        - has_resort_fees_warning
        - hotel
        - id
        - payments
        - readable_id
        - rooms
        - updated_at
    APIOrderHotelExt:
      type: object
      properties:
        address:
          type: string
        coordinates:
          $ref: '#/components/schemas/Location'
        facilities:
          type: array
          items:
            type: string
        id:
          type: string
        name:
          type: string
        phone:
          type: string
        property_category:
          $ref: '#/components/schemas/PropertyType'
        property_descriptions:
          type: array
          items:
            $ref: '#/components/schemas/PropertyDescription'
        star_rating:
          type: integer
          minimum: -9223372036854776000
          maximum: 9223372036854776000
        zip_code:
          type: string
      required:
        - coordinates
        - facilities
        - id
        - name
        - property_category
        - property_descriptions
    APIOrderRoomExt:
      type: object
      properties:
        adult_guests:
          type: integer
          minimum: 0
          maximum: 255
        bed_type:
          type: string
        booking_remarks:
          type: array
          items:
            type: string
        booking_status:
          $ref: '#/components/schemas/APIRoomStatus'
        facilities:
          type: array
          items:
            type: string
        id:
          $ref: '#/components/schemas/UUID'
        kids_ages:
          type: array
          items:
            type: integer
            minimum: 0
            maximum: 255
        lead_guest:
          $ref: '#/components/schemas/APIOrderGuest'
        meal_plan:
          $ref: '#/components/schemas/MealPlan'
        name:
          type: string
        refund_status:
          $ref: '#/components/schemas/APIRefundStatus'
        status_updated_at:
          $ref: '#/components/schemas/UTCTime'
      required:
        - adult_guests
        - facilities
        - id
        - kids_ages
        - lead_guest
        - name
        - status_updated_at
    APIGetRoomsRequest:
      type: object
      properties:
        hotel_id:
          type: string
        session_id:
          $ref: '#/components/schemas/UUID'
      required:
        - hotel_id
        - session_id
    APIGetRoomsResponse:
      type: object
      properties:
        common_categories:
          type: array
          items:
            $ref: '#/components/schemas/APICommonCategory'
        room_offers:
          type: array
          items:
            $ref: '#/components/schemas/APIRoomOffer'
        rooms_content:
          type: array
          items:
            $ref: '#/components/schemas/APIRoomContent'
        session_id:
          $ref: '#/components/schemas/UUID'
      required:
        - common_categories
        - room_offers
        - rooms_content
        - session_id
    APICommonCategory:
      type: object
      properties:
        common_facilities:
          type: array
          items:
            type: string
        name:
          type: string
      required:
        - common_facilities
        - name
    APIRoomOffer:
      type: object
      properties:
        booking_remarks:
          type: string
        cancellation_policies:
          type: array
          items:
            $ref: '#/components/schemas/CancellationPolicy'
        has_resort_fees_warning:
          type: boolean
        hotel_id:
          type: string
        refundability:
          $ref: '#/components/schemas/APIRefundability'
        room_offer_id:
          type: string
        room_offer_price:
          $ref: '#/components/schemas/APIPrice'
        rooms:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/APIRoom'
        simple_price:
          type: number
          multipleOf: 0.01
        supplier_id:
          type: string
        supplier_name:
          type: string
      required:
        - cancellation_policies
        - has_resort_fees_warning
        - room_offer_id
        - rooms
        - supplier_id
        - supplier_name
    APIRefundability:
      type: string
      enum:
        - unknown
        - refundable
        - nonrefundable
    APIPrice:
      type: object
      properties:
        commission:
          type: number
          multipleOf: 0.01
        final_price:
          type: number
          multipleOf: 0.01
        final_tax:
          type: number
          multipleOf: 0.01
        taxes_and_fees:
          type: array
          items:
            $ref: '#/components/schemas/APITaxesAndFees'
      required:
        - taxes_and_fees
    APIRoom:
      type: object
      properties:
        adults_count:
          type: integer
          minimum: 0
          maximum: 255
        bed_type:
          type: string
        description:
          type: string
        dtt_pricing:
          $ref: '#/components/schemas/APIDttPricing'
        id:
          type: string
        kids_ages:
          type: array
          items:
            type: integer
            minimum: 0
            maximum: 17
        meal_plan:
          $ref: '#/components/schemas/MealPlan'
        room_name:
          type: string
        target_room_key:
          type: string
      required:
        - adults_count
        - dtt_pricing
        - id
        - kids_ages
        - room_name
    APIRoomContent:
      type: object
      properties:
        descriptions:
          type: array
          items:
            type: string
        facilities:
          type: array
          items:
            type: string
        images:
          type: array
          items:
            $ref: '#/components/schemas/APIImage'
        target_room_key:
          type: string
      required:
        - descriptions
        - facilities
        - images
    APIImage:
      type: object
      properties:
        desc:
          type: string
        image_size:
          $ref: '#/components/schemas/ImageSize'
        url:
          type: string
      required:
        - url
    ImageSize:
      type: string
      enum:
        - standard
        - xl
    APIHotelProperties:
      type: object
      properties:
        advantages:
          type: array
          items:
            type: string
        detailed_description:
          type: array
          items:
            $ref: '#/components/schemas/DetailedDescriptionItem'
        facility_categories:
          type: array
          items:
            $ref: '#/components/schemas/FacilityCategoriesItem'
        images:
          type: array
          items:
            $ref: '#/components/schemas/APIImage'
        long_description:
          type: array
          items:
            type: string
        policies:
          type: array
          items:
            $ref: '#/components/schemas/PoliciesItem'
        short_description:
          type: array
          items:
            type: string
        typical_description:
          type: array
          items:
            type: string
      required:
        - advantages
        - detailed_description
        - facility_categories
        - images
        - long_description
        - policies
        - short_description
        - typical_description
    DetailedDescriptionItem:
      type: object
      properties:
        paragraphs:
          type: array
          minItems: 1
          items:
            type: string
        title:
          type: string
      required:
        - paragraphs
    FacilityCategoriesItem:
      type: object
      properties:
        facilities:
          type: array
          items:
            type: string
        name:
          type: string
      required:
        - facilities
        - name
    PoliciesItem:
      type: object
      properties:
        paragraphs:
          type: array
          minItems: 1
          items:
            type: string
        title:
          type: string
      required:
        - paragraphs
        - title
